import { Order } from '../entities/Order';
import type { OrderRepository } from '../repositories/OrderRepository';
import { OrderItem } from '../value-objects/OrderItem';

export interface CreateOrderRequest {
  customerId: string;
  items: Array<{
    productId: string;
    quantity: number;
    unitPrice: number;
  }>;
  discount?: number;
  notes?: string;
}

export class CreateOrder {
  constructor(private orderRepo: OrderRepository) {}

  async execute(request: CreateOrderRequest): Promise<Order> {
    // Validate request
    if (!request.customerId) {
      throw new Error('Customer ID is required');
    }
    if (!request.items || request.items.length === 0) {
      throw new Error('Order must have at least one item');
    }

    // Create order items
    const orderItems = request.items.map((item) =>
      OrderItem.create(item.productId, item.quantity, item.unitPrice)
    );

    // Calculate totals
    const subtotal = orderItems.reduce((sum, item) => sum + item.subtotal, 0);
    const discount = request.discount || 0;
    const total = subtotal - discount;

    // Create order entity
    const order = new Order(
      '', // ID will be generated by database
      request.customerId,
      orderItems,
      subtotal,
      discount,
      total,
      'pendiente',
      request.notes,
      new Date(),
      new Date()
    );

    // Save to repository
    return await this.orderRepo.create(order);
  }
}
