import { Customer } from '../entities/Customer';
import type { CustomerRepository } from '../repositories/CustomerRepository';

export interface RegisterCustomerRequest {
  firstName: string;
  lastName: string;
  email: string;
  phone?: string;
}

export class RegisterCustomer {
  constructor(private customerRepo: CustomerRepository) {}

  async execute(request: RegisterCustomerRequest): Promise<Customer> {
    // Validate required fields
    if (!request.firstName || !request.lastName || !request.email) {
      throw new Error('First name, last name, and email are required');
    }

    // Check if email already exists
    const existingCustomer = await this.customerRepo.findByEmail(request.email);
    if (existingCustomer) {
      throw new Error(`Customer with email ${request.email} already exists`);
    }

    // Create customer entity
    const customer = new Customer(
      '', // ID will be generated by database
      request.firstName,
      request.lastName,
      request.email,
      request.phone
    );

    // Save to repository
    return await this.customerRepo.create(customer);
  }
}
